const CARD_VARIANT = {
	ANGULAR: 'angular',
	JS: 'javascript',
	VUE: 'vue js',
	REACT: 'react',
	SCSS: 'scss',
	NODEJS: 'nodejs',
	HTML: 'html',
	CSS: 'css',
	MYSQL: 'mysql',
	GITHUB: 'github',
};

export const CARDS_DATA: CardType[] = [
	{
		img: '/images/angular.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.ANGULAR,
	},
	{
		img: '/images/angular.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.ANGULAR,
	},
	{
		img: '/images/react.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.REACT,
	},
	{
		img: '/images/react.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.REACT,
	},
	{
		img: '/images/scss.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.SCSS,
	},
	{
		img: '/images/scss.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.SCSS,
	},
	{
		img: '/images/nodejs.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.NODEJS,
	},
	{
		img: '/images/nodejs.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.NODEJS,
	},
	{
		img: '/images/html.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.HTML,
	},
	{
		img: '/images/html.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.HTML,
	},
	{
		img: '/images/css.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.CSS,
	},
	{
		img: '/images/css.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.CSS,
	},
	{
		img: '/images/js.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.JS,
	},
	{
		img: '/images/js.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.JS,
	},
	{
		img: '/images/mysql.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.MYSQL,
	},
	{
		img: '/images/mysql.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.MYSQL,
	},
	{
		img: '/images/github.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.GITHUB,
	},
	{
		img: '/images/github.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.GITHUB,
	},
	{
		img: '/images/vue.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.VUE,
	},
	{
		img: '/images/vue.png',
		isActive: true,
		isMatched: false,
		variant: CARD_VARIANT.VUE,
	},
];
