const CARDS_INACTIVE_TIMER = 2500;
const CARDS_FLASH_TIMER = 100;
const CARD_MATCH_DELAY = 360;
const ALERT_DIALOG_TIMEOUT = 800;

export {
	CARDS_INACTIVE_TIMER,
	CARDS_FLASH_TIMER,
	CARD_MATCH_DELAY,
	ALERT_DIALOG_TIMEOUT,
};
